# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlogotterMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BlogotterMobile

  pod 'Firebase/Core', '~> 4.13.0'
  pod 'Firebase/Database', '~> 4.13.0'
  pod 'Firebase/Auth'
  pod 'GoogleToolboxForMac'
  pod 'GoogleSignIn'
  pod 'Firebase/Analytics', '4.13.0'

  #target 'BlogotterMobile-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

  target 'BlogotterMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'BlogotterMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BlogotterMobile-tvOS

#  target 'BlogotterMobile-tvOSTests' do
#    inherit! :search_paths
    # Pods for testing
#  end

#end
